name: Backend CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "7.0.405" # Specifying exact version

      - name: Install dependencies
        run: dotnet restore
        timeout-minutes: 10

      - name: Build
        run: dotnet build --configuration Release --no-restore
        timeout-minutes: 15

      - name: Test
        run: dotnet test --no-restore --verbosity normal
        timeout-minutes: 10

      - name: Publish
        run: dotnet publish -c Release -o published
        timeout-minutes: 10

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: "ChessDotnet"
          package: published
